settings:
  rule: '-'
  ruleRepetition: 3
  ruleSpaces: false

  bullet: '-'

plugins:
  - remark-parse
  - - remark-frontmatter
    - type: yaml
      marker: '-'
  - - remark-gfm
    - tablePipeAlign: false
  - remark-lint
  - - remark-lint-frontmatter-schema
    - schemas:
        ./tools/docs/schemas/spec-frontmatter.schema.yaml:
          - ./docs/**/*.md
        ./tools/docs/schemas/bdd.schema.yaml:
          - ./docs/**/bdd-*.yaml
        ./tools/docs/schemas/esil.schema.yaml:
          - ./docs/**/esil-*.yaml
