openapi: 3.0.3
info:
  title: 駄菓子屋業務システム API
  version: 1.0.0

paths:
  /api/sales:
    post:
      summary: 販売登録
      operationId: createSale
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                soldAt:
                  type: string
                  format: date-time
                paymentType:
                  type: string
                  enum: [cash, credit]
                customerId:
                  type: string
                  nullable: true
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                      quantity:
                        type: integer
                      unitPrice:
                        type: integer
      responses:
        '201':
          description: 販売登録成功
        '400':
          description: 不正な入力（つけ限度額超過など）
  /api/inventories:
    get:
      summary: 在庫一覧取得
      parameters:
        - in: query
          name: favoriteOnly
          schema:
            type: boolean
      responses:
        '200':
          description: 正常
